routes/web.php
<?php


Route::get('/', function () {
     return redirect('/login');
});

Auth::routes(['verify' => true]);
    
Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'Web\ProfieController@index')->name('profile.index');
    Route::post('profile', 'Web\ProfieController@store')->name('profile.store');
    Route::post('profile/update-email', 'Web\ProfieController@updateEmail')->name('profile.update.email');
    Route::post('profile/update-password', 'Web\ProfieController@updatePassword')->name('profile.update.password');
});

Route::group(['middleware' => ['verified', 'auth']], function () {
    Route::get('/dashboard', 'HomeController@index')->name('home');

    Route::resource('project', 'Project\ProjectController');
    Route::post('/project/{project}/invite', 'Project\ProjectController@invite')->name('project.invite');

    Route::get('/project/{project}/todo', 'Project\TodoController@index')->name('todo.index');
    Route::post('/project/{project}/todo', 'Project\TodoController@store')->name('todo.store'); 

    Route::resource('todo', 'Project\TodoController')->except([
        'index', 'create'
    ]);

    Route::post('/todo/{todo}/invite', 'Project\TodoController@invite')->name('project.invite');
    Route::post('/todo/{todo}/update-status', 'Project\TodoController@updateStatus')->name('todo.update.status');
    Route::post('/todo/{todo}/change-due-date', 'Project\TodoController@changeDueDate')->name('todo.change.date');
    Route::post('/todo/{project}/order', 'Project\TodoController@updateOrder')->name('todo.update.order');

    Route::post('/task/{task}/update/done', 'Project\TaskController@updateDone')->name('task.update.done');
    Route::post('/todo/{todo}/task', 'Project\TaskController@store')->name('task.store');

    Route::get('/discussion/{id}/{type}', 'Project\DiscussionController@getDiscussion')->name('discussion.get');
    Route::post('/discussion/{id}/{type}', 'Project\DiscussionController@sendDiscussion')->name('discussion.send');

    Route::apiResource('company', 'Web\CompanyController')->except([
        'show', 'destroy'
    ]);
    Route::post('/company/{company}/invite', 'Web\CompanyController@invite')->name('company.invite');
    Route::post('/company/{company}/detach', 'Web\CompanyController@detach')->name('company.detach');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('style')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('profile.index') }}">
                                        Profile
                                    </a>
                                    <a class="dropdown-item" href="{{ route('company.index') }}">
                                        Company
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

@yield('script')
</html>